-- VayuDrishti Admin Suite Database Migration
-- Implements Complaints, Tasks, Alerts, and Audit Logs

-- ==========================================
-- 1. ENUMS
-- ==========================================
CREATE TYPE complaint_status AS ENUM ('NEW', 'UNDER_REVIEW', 'IN_ACTION', 'RESOLVED', 'REJECTED');
CREATE TYPE task_priority AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
CREATE TYPE task_status AS ENUM ('PENDING', 'IN_PROGRESS', 'COMPLETED');
CREATE TYPE alert_severity AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
CREATE TYPE alert_trigger AS ENUM ('AQI_SPIKE', 'REPEATED_COMPLAINTS', 'HOTSPOT');

-- ==========================================
-- 2. TABLES
-- ==========================================

-- A. Complaints Management
CREATE TABLE IF NOT EXISTS public.complaints (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  citizen_id UUID REFERENCES public.profiles(id) NOT NULL,
  location_lat DOUBLE PRECISION NOT NULL,
  location_lon DOUBLE PRECISION NOT NULL,
  ward TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  media_url TEXT,
  status complaint_status DEFAULT 'NEW' NOT NULL,
  assigned_to UUID REFERENCES public.profiles(id),
  internal_notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  resolved_at TIMESTAMPTZ
);

-- B. Task & Action Board (Assigned to Officers / Admins)
CREATE TABLE IF NOT EXISTS public.tasks (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  complaint_id UUID REFERENCES public.complaints(id), -- Nullable for Ad-hoc tasks
  assignee_id UUID REFERENCES public.profiles(id),
  title TEXT NOT NULL,
  description TEXT,
  priority task_priority DEFAULT 'MEDIUM' NOT NULL,
  status task_status DEFAULT 'PENDING' NOT NULL,
  deadline TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

-- C. Real-time System Alerts (Auto-generated by ML / Analytics)
CREATE TABLE IF NOT EXISTS public.alerts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  ward TEXT NOT NULL,
  trigger_type alert_trigger NOT NULL,
  severity alert_severity DEFAULT 'HIGH' NOT NULL,
  is_acknowledged BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- D. Mandatory Audit Logging (Zero silent-actions policy)
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  actor_id UUID REFERENCES public.profiles(id),
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL, -- 'complaint', 'task', 'profile'
  entity_id UUID NOT NULL,
  old_data JSONB,
  new_data JSONB,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 3. ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================

ALTER TABLE public.complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
-- Audit logs should be read-only (and only insertable by Triggers/SuperAdmins), but enforcing via API too
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Complaints Access: Citizens can see their own. Admins/Officers see all.
CREATE POLICY "Complaints - Citizen Select" ON public.complaints FOR SELECT USING (auth.uid() = citizen_id);
CREATE POLICY "Complaints - Staff Select" ON public.complaints FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND role IN ('admin', 'officer'))
);
CREATE POLICY "Complaints - Citizen Insert" ON public.complaints FOR INSERT WITH CHECK (auth.uid() = citizen_id);
CREATE POLICY "Complaints - Staff Update" ON public.complaints FOR UPDATE USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND role IN ('admin', 'officer'))
);

-- Tasks Access: Staff only
CREATE POLICY "Tasks - Staff Select" ON public.tasks FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND role IN ('admin', 'officer'))
);
CREATE POLICY "Tasks - Staff Update" ON public.tasks FOR UPDATE USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND role IN ('admin', 'officer'))
);
CREATE POLICY "Tasks - Admin Insert" ON public.tasks FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND role = 'admin')
);

-- Alerts Access: Staff only
CREATE POLICY "Alerts - Staff Select" ON public.alerts FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND role IN ('admin', 'officer'))
);
CREATE POLICY "Alerts - Staff Update" ON public.alerts FOR UPDATE USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND role IN ('admin', 'officer'))
);

-- Audit Logs Access: Staff Select ONLY. Triggers will bypass RLS.
CREATE POLICY "Audit - Staff Select" ON public.audit_logs FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND role IN ('admin', 'officer'))
);

-- ==========================================
-- 4. DATABASE-LEVEL AUDIT TRIGGERS
-- ==========================================

-- Function to generically log row updates into audit_logs
CREATE OR REPLACE FUNCTION log_audit_event()
RETURNS TRIGGER AS $$
DECLARE
  current_user_id UUID;
BEGIN
  -- We assume standard Supabase auth execution, auth.uid() returns the actor.
  current_user_id := auth.uid();
  
  IF TG_OP = 'UPDATE' THEN
    INSERT INTO public.audit_logs (actor_id, action, entity_type, entity_id, old_data, new_data)
    VALUES (
      current_user_id,
      'UPDATE ' || UPPER(TG_TABLE_NAME),
      TG_TABLE_NAME,
      NEW.id,
      row_to_json(OLD)::JSONB,
      row_to_json(NEW)::JSONB
    );
    RETURN NEW;
  ELSIF TG_OP = 'INSERT' THEN
    INSERT INTO public.audit_logs (actor_id, action, entity_type, entity_id, old_data, new_data)
    VALUES (
      current_user_id,
      'INSERT ' || UPPER(TG_TABLE_NAME),
      TG_TABLE_NAME,
      NEW.id,
      NULL,
      row_to_json(NEW)::JSONB
    );
    RETURN NEW;
  END IF;
  
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Map triggers to tables
CREATE TRIGGER audit_complaints_changes
  AFTER INSERT OR UPDATE ON public.complaints
  FOR EACH ROW EXECUTE PROCEDURE log_audit_event();

CREATE TRIGGER audit_tasks_changes
  AFTER INSERT OR UPDATE ON public.tasks
  FOR EACH ROW EXECUTE PROCEDURE log_audit_event();
